adapter: postgres

development:
  host: localhost
  port: 3306
  username: root
  password: root
  database: tablename

production:
  host: localhost
  port: 3306
  username: root
  password: root
  database: tablename
