# Info
name:        Project name
description: Project description
baseurl:     /
url:         http://www.vitorbritto.com.br

# Config
source:      .
destination: ./_build
permalink:   /:title/
markdown:    kramdown
exclude: [
bower.json,
package.json,
Gruntfile.js,
config.rb,
.editorconfig,
.gitignore,
.jshintrc,
Rakefile,
Gemfile,
Gemfile.lock,
sass,
node_modules,
legacy,
main.js,
README.md
]

# Custom
twitter:    https://twitter.com/projectname
facebook:   https://www.facebook.com/projectname
