sudo: false
language: php
php:
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - jspm_modules
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g babel gulp
  - npm install
